[UPDATE] Speciality entity
roman89ua/IF-105.UI.dtapi.if.ua.io pull request #14
Opened 2020-01-14 14:20 UTC by kravtsivkostya

### Added possibility to update and create speciality records by using dialog-form window.
Needs to be done: styling, databingding to display data for object in update form, error handling and pagination

2020-01-15 09:39 UTC, AndriyIf requested changes

2020-01-15 09:39 UTC, AndriyIf commented on src/app/admin/speciality/speciality-list/speciality-list.component.ts
> +  Speciality: Speciality[] = [];
Should be started from lowercase letter.

2020-01-15 09:39 UTC, AndriyIf commented on src/app/admin/speciality/speciality-list/speciality-list.component.ts
>    public entity = 'Speciality';
In case you use `public` you should use it for all properties. Or you can just skip it. In TS `public` is default access control modifier.

2020-01-16 13:35 UTC, kravtsivkostya reviewed
applied changes

2020-01-16 14:39 UTC, AndriyIf approved these changes

2020-01-16 15:01 UTC, zikratyi approved these changes

2020-01-16 15:01 UTC, merged